CREATE TABLE ACCOUNT
(
    id         INT NOT NULL,
    BALANCE    decimal(15, 2),
    CURRENCY   VARCHAR(10),
    CREATED_AT DATE,
    PRIMARY KEY (id)
);

CREATE TABLE TRANSACTION
(
    id                INT NOT NULL,
    SOURCE_ACCOUNT_ID INT NOT NULL,
    TARGET_ACCOUNT_ID INT NOT NULL,
    AMOUNT            decimal(15, 2),
    CURRENCY          VARCHAR(10),
    PRIMARY KEY (id),
    FOREIGN KEY (SOURCE_ACCOUNT_ID) REFERENCES ACCOUNT(id),
    FOREIGN KEY (TARGET_ACCOUNT_ID) REFERENCES ACCOUNT(id)
);

INSERT INTO ACCOUNT VALUES (123456789, 10.2, 'EUR', '2024-01-01');
INSERT INTO ACCOUNT VALUES (987654321, 5.2, 'EUR', '2024-02-01');